# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kecs < Formula
  desc "Kubernetes-based ECS Compatible Service - Run ECS workloads on Kubernetes"
  homepage "https://github.com/nandemo-ya/kecs"
  version "0.0.1-beta.5"
  license "Apache-2.0"

  depends_on "docker" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.5/kecs_0.0.1-beta.5_Darwin_x86_64.tar.gz"
      sha256 "6ecc78ad1012ad1fe9b24c6e5b7c63b9ccea34cd02a6984de1593d4af7c0a7e0"

      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.5/kecs_0.0.1-beta.5_Darwin_arm64.tar.gz"
      sha256 "d188747e999d98a248ebed2a0df9601ade8c4e1d73f93b60e335e3c8d888d43b"

      def install
        bin.install "kecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.5/kecs_0.0.1-beta.5_Linux_x86_64.tar.gz"
      sha256 "c032e80e813bd81a8c4a0684795d1187ba55ae098b5fe929b18d5d3f7e93f964"
      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.5/kecs_0.0.1-beta.5_Linux_arm64.tar.gz"
      sha256 "80594c087cbd086ea60e84efd15911134235f7d6e3d89100dd1bac64dd018fb8"
      def install
        bin.install "kecs"
      end
    end
  end

  def caveats
    <<~EOS
      KECS requires a Kubernetes cluster to run workloads.
      For local development, you can use:
        - Docker Desktop with Kubernetes enabled
        - k3d: brew install k3d
        - kind: brew install kind

      Quick start:
        kecs start  # Start KECS in a container
        kecs status # Check status

      For more information:
        https://github.com/nandemo-ya/kecs
    EOS
  end

  test do
    system "#{bin}/kecs", "version"
  end
end
