# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kecs < Formula
  desc "Kubernetes-based ECS Compatible Service - Run ECS workloads on Kubernetes"
  homepage "https://github.com/nandemo-ya/kecs"
  version "0.0.1-beta.3"
  license "Apache-2.0"

  depends_on "docker" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.3/kecs_0.0.1-beta.3_Darwin_x86_64.tar.gz"
      sha256 "5807b85a55517549399b40c10e970cac3ba86fc6c9a3edf1021cbde0440a1e4a"

      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.3/kecs_0.0.1-beta.3_Darwin_arm64.tar.gz"
      sha256 "361eba25439ff868ed5eaa0fb1b00805f866fa23782f43d36dcabb3d2068855d"

      def install
        bin.install "kecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.3/kecs_0.0.1-beta.3_Linux_x86_64.tar.gz"
      sha256 "6c45e8ad77e3e995b071906cd08e617453108ec7f798ebd69044e295d459018f"
      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-beta.3/kecs_0.0.1-beta.3_Linux_arm64.tar.gz"
      sha256 "dbcf52390ad038f54d48017efa4bec47b91527d2cdd4360cba223478eb3c358e"
      def install
        bin.install "kecs"
      end
    end
  end

  def caveats
    <<~EOS
      KECS requires a Kubernetes cluster to run workloads.
      For local development, you can use:
        - Docker Desktop with Kubernetes enabled
        - k3d: brew install k3d
        - kind: brew install kind

      Quick start:
        kecs start  # Start KECS in a container
        kecs status # Check status

      For more information:
        https://github.com/nandemo-ya/kecs
    EOS
  end

  test do
    system "#{bin}/kecs", "version"
  end
end
