# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kecs < Formula
  desc "Kubernetes-based ECS Compatible Service - Run ECS workloads on Kubernetes"
  homepage "https://github.com/nandemo-ya/kecs"
  version "0.0.1-pre.10"
  license "Apache-2.0"

  depends_on "docker" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-pre.10/kecs_0.0.1-pre.10_Darwin_x86_64.tar.gz"
      sha256 "1bcca0ad5be16fabd0a42d629fb0f01b63c8cbf099896234d85339fa380dc793"

      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-pre.10/kecs_0.0.1-pre.10_Darwin_arm64.tar.gz"
      sha256 "5ff4a251ee195757f5142fae3a4a5ab957c770374951bd6628a6c2cd81c40861"

      def install
        bin.install "kecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-pre.10/kecs_0.0.1-pre.10_Linux_x86_64.tar.gz"
      sha256 "7c48d82208b6b52c5b3b3c5b37cfe49ec602af8167408b617bfbeb27e312910d"
      def install
        bin.install "kecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nandemo-ya/kecs/releases/download/v0.0.1-pre.10/kecs_0.0.1-pre.10_Linux_arm64.tar.gz"
      sha256 "fd3a406a82b541bfc09ef56d176298e42c50e0bdc97501082b04193683401382"
      def install
        bin.install "kecs"
      end
    end
  end

  def caveats
    <<~EOS
      KECS requires a Kubernetes cluster to run workloads.
      For local development, you can use:
        - Docker Desktop with Kubernetes enabled
        - k3d: brew install k3d
        - kind: brew install kind

      Quick start:
        kecs start  # Start KECS in a container
        kecs status # Check status

      For more information:
        https://github.com/nandemo-ya/kecs
    EOS
  end

  test do
    system "#{bin}/kecs", "version"
  end
end
